### ISSUE TITLE
Am I supposed to not be able to shoot through chunk borders?

### ISSUE THREAD

**Issue by DogeisCut** [Mee12345/gmod-infinite-map#102]
It just seems like a thing that should exist considering your portal mod can do it.

**Comment by pizzamagician** [comment]
why don't you make it yourself then

**Comment by Mee12345** [comment]
cross chunk traceline and bullets were not added as a feature because of the massive overhead

**Comment by DogeisCut** [comment]
In hindsight, i realise why this isnt a feature, cause there is still the issue of making the bullets not effect the current chunk
