### ISSUE TITLE
LFS Land Vehicles zoom away after driving out of a chunk.

### ISSUE THREAD

**Issue by Spart2934B** [Mee12345/gmod-infinite-map#107]
I guess this a lfs issue itself and it can't be fixed? 
It mostly happens at full throttle. 

https://user-images.githubusercontent.com/121526065/209743432-6bb2fd73-b794-4a09-99bc-eeb80f8780f6.mp4

**Comment by Mee12345** [comment]
looks like its failing to teleport it and only updating its chunk information, not sure what the problem is here

**Comment by Mee12345** [comment]
the LFS base has been replaced with LVS, which has better infmap support
