### ISSUE TITLE
Setting InfMap.chunk_size < 1000 breaks stuff

### ISSUE THREAD

**Issue by IntellectualPotato** [Mee12345/gmod-infinite-map#108]
So upon setting InfMap.chunk_size to 176 (yes very small.) the spawning and rendering of prop_physics breaks between chunks and most likely other spawned things, However untested. No idea why this happens but it would be nice if it was fixed!

**Comment by Mee12345** [comment]
ah, thanks for reporting. should be fixed (though, I highly suggest not setting it any lower than 1000)
