### ISSUE TITLE
Better placeholder cubemap?

### ISSUE THREAD

**Issue by mrwallace888** [Mee12345/GMod-Infinite-Map#11]
Was just wondering if you could make a placeholder grassy blue sky cubemap for the map since the existing default one doesn't match and is also insanely bright.

**Comment by DarianLStephens** [comment]
Ah. I was going to ask about maybe doing that named light_environment thing so that CSM can work better with it, but that's probably a bit out of your control, as well.

**Comment by kevinmlgnoscope** [comment]
maybe try using the addon "improved default cubemap"? im not sure it will help but possibly?

**Comment by DarianLStephens** [comment]
That addon does help, actually!

**Comment by Mee12345** [comment]
the cubemap has been altered and there is now less bloom
