### ISSUE TITLE
change in InWater() function from local to global

### ISSUE THREAD

**Issue by Miguelito223** [Mee12345/gmod-infinite-map#110]
I'm saying this because I want to make this mod compatible with my mod called gdisasters revived and since it has an oxygen and body temperature system, I want to make this system work with this mod when it's underwater but it doesn't work and the problem It is that this function is local so if you can change that would make me happy

**Comment by TheVogels** [comment]
### > I'm saying this because I want to make this mod compatible with my mod called gdisasters revived and since it has an oxygen and body temperature system, I want to make this system work with this mod when it's underwater but it doesn't work and the problem It is that this function is local so if you can change that would make me happy

You can make it so the client send it to the server if the client is in water.

**Comment by TheVogels** [comment]
> I'm saying this because I want to make this mod compatible with my mod called gdisasters revived and since it has an oxygen and body temperature system, I want to make this system work with this mod when it's underwater but it doesn't work and the problem It is that this function is local so if you can change that would make me happy

You can make it so the client send it to the server if the client is in water.

**Comment by Miguelito223** [comment]
> 
ok thanks, I looked at the code and I saw that the InfMap.water_height variable was global, also that the water level of the map is always at -5000, so I already found the solution, it was very easy but I made it complicated.

**Comment by Miguelito223** [comment]
> > I'm saying this because I want to make this mod compatible with my mod called gdisasters revived and since it has an oxygen and body temperature system, I want to make this system work with this mod when it's underwater but it doesn't work and the problem It is that this function is local so if you can change that would make me happy
> 
> You can make it so the client send it to the server if the client is in water.
> 
> Notice: I don't know so much about Gmod lua calls/commands.

ok thanks, I looked at the code and I saw that the InfMap.water_height variable was global, also that the water level of the map is always at -5000, so I already found the solution, it was very easy but I made it complicated.

**Comment by Mee12345** [comment]
Making gdisasters compatible with this map sounds like a huge pain in the ass (especially with the particles), best of luck to you
