### ISSUE TITLE
the map is sideways

### ISSUE THREAD

**Issue by clone124642** [Mee12345/gmod-infinite-map#111]
the collisions are normal but the mesh/visuals are sideways it may be due to me not having the orginal bin file or it could be becau- i don't know anymore...
![4000_screenshots_20221227125707_1](https://user-images.githubusercontent.com/121694892/210111394-e705d240-5e21-411f-9f1d-5452905c4c8b.jpg)
![4000_screenshots_20221214223448_1](https://user-images.githubusercontent.com/121694892/210111407-a752d385-ff5a-41bb-a40e-bfa6b17e516e.jpg)

**Comment by xCeezyx** [comment]
Might be a extremely weird addon colfiction

**Comment by clone124642** [comment]
> It might be an extremely weird addon confliction

yeah uh, i deleted all the addons and it is still there...

**Comment by clone124642** [comment]
BLESS THE GODS IT IS FIXED

**Comment by Mee12345** [comment]
i dont know what causes this so any indication of what happened and how you fixed it would be appreciated

**Comment by clone124642** [comment]
> i dont know what causes this so any indication of what happened and how you fixed it would be appreciated

not gonna lie my bin folder was deleted so i had to replace it with the hl2 bin folder, then i installed gmad and it somehow fixed it

**Comment by clone124642** [comment]
just speculations

**Comment by clone124642** [comment]
new issue has risen...
![20230105150444_1](https://user-images.githubusercontent.com/121694892/210798619-8a442082-48b2-4e49-b7a4-fe03b3fcdb3f.jpg)

**Comment by DarianLStephens** [comment]
And that is...? The colors?

**Comment by clone124642** [comment]
> And that is...? The colors?

random ass addon i have

**Comment by Mee12345** [comment]
I think im gonna label this as addon confliction
