### ISSUE TITLE
make wiremod water sensor work better

### ISSUE THREAD

**Issue by LucasAiden** [Mee12345/gmod-infinite-map#113]
so wiremod ships and sea monsters work better

**Comment by LucasAiden** [comment]
the sensor dosent detect water

**Comment by xCeezyx** [comment]
Thats because the water in the mod is fake water not source water

**Comment by LucasAiden** [comment]
but its eazy to fix it, like:
if sensor.y < water_level then
   sensor.out = true
else
   sensor.out = false
end

**Comment by Mee12345** [comment]
feel free to add it urself, the code is open source
the reason im not doing it because it would make the code messier

**Comment by Mee12345** [comment]
duplicate of https://github.com/Mee12345/gmod-infinite-map/issues/81
