### ISSUE TITLE
Gravity gun can punt ground.

### ISSUE THREAD

**Issue by TheVogels** [Mee12345/gmod-infinite-map#117]
The item "weapon_physcannon" can punt the ground.

I'm not sure if this is just a weird entity in the flatgrass map.

It's a entity.

**Comment by Bonyoze** [comment]
should be a simple fix:
```lua
function ENT:GravGunPunt()
	return true
end
```

**Comment by TheVogels** [comment]
I just realized that is just a bugged entity in the map.
