### ISSUE TITLE
invinible walls...

### ISSUE THREAD

**Issue by clone124642** [Mee12345/gmod-infinite-map#118]
![20230220003833_1](https://user-images.githubusercontent.com/121694892/219982730-67568e16-d59d-46a9-b2a4-3c4a361f482e.jpg)

as you can see i am shooting the mentioned invisible wall with an smg

**Comment by clone124642** [comment]
i don't know what's causing this but it's honestly very weird

**Comment by Mee12345** [comment]
have you checked for addon conflictions?

**Comment by clone124642** [comment]
the console says nothing...

**Comment by Mee12345** [comment]
Not having any errors doesn't mean there isn't a confliction. Try disabling all your addons and see if the problem persists

**Comment by clone124642** [comment]
ight imma see, yep some kind of weird addon confliction...

**Comment by clone124642** [comment]
is there an some kind of list of incompatible addons?

**Comment by Mee12345** [comment]
No, but it would be nice though if you had the addon that caused the issue

**Comment by clone124642** [comment]
pikmin NEW somehow enabled the invisible walls issue is now apparent
