### ISSUE TITLE
Spawning Source vehicles breaks the game.

### ISSUE THREAD

**Issue by mrwallace888** [Mee12345/GMod-Infinite-Map#14]
When spawning a regular Source vehicle, I get a notification saying the map is creating an error. Source vehicles spawn in mid-air at the center of the map with no collisions nor any kind of interactivity. Cannot be removed either.

**Comment by Mee12345** [comment]
Are you on the latest version? This was a bug that was patched a few days ago

**Comment by Mee12345** [comment]
(Maybe it came back..?)

**Comment by mrwallace888** [comment]
Yeah I did.

**Comment by Mee12345** [comment]
can I have the error?
