### ISSUE TITLE
Far Plane Clipping

### ISSUE THREAD

**Issue by DarianLStephens** [Mee12345/GMod-Infinite-Map#18]
I'm not certain if this is one of those 'eventually' features, but your view is being clipped pretty close, a far cry from the '2 billion units' plan.

You can't see anything out there, just empty space.
![20221023155740_1](https://user-images.githubusercontent.com/15375876/197374641-1a4783eb-c846-43e3-abb3-afd75b47d475.jpg)
Until I turn so it's within the camera's far plane distance...
![20221023155749_1](https://user-images.githubusercontent.com/15375876/197374702-069b70e9-42da-4bd5-b859-1f213739e4c4.jpg)

Maybe there's a way to change that with console commands, but I don't know them.

**Comment by Mee12345** [comment]
the map has a farz value of 2.1 billion, im not sure why yours is being clipped early

(check for possibly conflicting addons?)
(calc view hook?)

**Comment by DarianLStephens** [comment]
Is there any way to find out which addon has that hook without just disabling them all and testing one by one?

**Comment by DarianLStephens** [comment]
Yeah, it was a conflict; it seems to be working fine now.
![20221023182857_1](https://user-images.githubusercontent.com/15375876/197379808-5b1f6ec2-f9f6-4b43-8d78-c968dda1c1bd.jpg)
I haven't gone through to find out which it was, but it's nice to have the full effect of the infinite map.

**Comment by Mee12345** [comment]
You could detour hook.add and see which addons are creating a CalcView hook

**Comment by DarianLStephens** [comment]
Binary search, yeah. I only had, like, 10 enabled, though, so I'm not sure it's worth doing that over just checking them one by one.

**Comment by TreeOfSelf** [comment]
of course the guy with the MLP avatar posts a bug report about their broken addons

**Comment by Mee12345** [comment]
closing since this is a confliction related to a poorly made addon

**Comment by DarianLStephens** [comment]
I believe it was the CSM mod.
