### ISSUE TITLE
Wire Camera & Target Finder

### ISSUE THREAD

**Issue by DarianLStephens** [Mee12345/GMod-Infinite-Map#19]
Both of these seem to have strange issues.
For the camera, it appears to always put your view at 0 0 0, or somewhere near it?
For the target finder, it's like it disregards neighbouring chunks, and only sees the main physical area, so if its target crosses a chunk border and there's another valid target 'closer', it will switch to that one.

**Comment by DarianLStephens** [comment]
To clarify, it's the Cam Controller, not just the RT camera.

**Comment by Mee12345** [comment]
the camera I don't think will be fixed, but in theory the target finder should now work fine thanks to liddle
