### ISSUE TITLE
glitchy textures

### ISSUE THREAD

**Issue by noaccessl** [Mee12345/GMod-Infinite-Map#2]
https://user-images.githubusercontent.com/54954576/196024371-c524c62e-f8be-43eb-9e6a-7c2aa76a009b.mp4

**Comment by Mee12345** [comment]
the plate is so big that source rendering breaks down a bit
since its only visual I wouldn't worry about it

**Comment by Mee12345** [comment]
new terrain is introduced so this shouldn't be a problem anymore
