### ISSUE TITLE
invisible ground

### ISSUE THREAD

**Issue by Idol11112222** [Mee12345/GMod-Infinite-Map#27]
good work!
![Screenshot_221](https://user-images.githubusercontent.com/105334854/198829446-b815318b-13f3-46ba-8b14-0f6ef98d98f8.png)

**Comment by DarianLStephens** [comment]
Calm down, it's probably just broken temporarily.
I tried it just a few commits ago, and the terrain was already mostly working, just with spikes and stuff.

**Comment by DarianLStephens** [comment]
Oh, actually, it only seems to be broken until you move to a different chunk:
![20221029230336_1](https://user-images.githubusercontent.com/15375876/198830351-64ad067b-c234-4135-ba82-fcf5862e0ced.jpg)
It's even fine after coming back to the original chunk, with the helicopter bomb gone:
![20221029230447_1](https://user-images.githubusercontent.com/15375876/198830388-b0866c31-61c1-478b-bea8-655f08b1802e.jpg)

The big flat area's a great touch, but it does make me long for the potential of terrain editing.

**Comment by whenisthedoor** [comment]
when i load into map there is no terrain

**Comment by Mee12345** [comment]
should be fixed

**Comment by DarianLStephens** [comment]
It does indeed appear to be fixed!
