### ISSUE TITLE
Audio isn't offset when moving between chunks

### ISSUE THREAD

**Issue by blackflash4088** [Mee12345/GMod-Infinite-Map#28]
Audio source location isn't offset when being moved between chunks.

**Comment by blackflash4088** [comment]
Many other things aren't being offset either, including particle effects and bullets and other projectiles. I'm assuming these aren't bugs, but rather something that hasn't yet been implemented.

**Comment by Mee12345** [comment]
technically fixed but its super shit, source sounds are very broken and the current detour is the best I can do
