### ISSUE TITLE
the suggestions thread (note most of these would be a very big undertaking so nothing is expected)

### ISSUE THREAD

**Issue by Redd56** [Mee12345/GMod-Infinite-Map#29]
1: biomes. once yiou have trees implimented (if your going to) multiple ground textures, rock textures and tree textures, maybe just 2 to start with, that way it adds just a bit of variation

examples of biomes that we could see: 
something like a snowy one
something like a plains biome where the ground is mostly flat
maybe a large rocky one that has lots of rocks and few trees but in some areas a bit of grass and small bush or two
a sprawling forest with a river or pond

**Comment by Redd56** [comment]
editing tools, Would this be hard to make, yes, but i think if it was implimented it would not only be cool but would have a chance to propel the map into being a staple of gmod, one that can house more than just infinite hills but in fact is a map creation tool itself (when mixed with other assets etc) 

My thought on what could be editor tools: 
flatener (flattens terraign to one level set by the tool), 
roundener (makes things smooth and round)
restoration tool: (makes the selected area and radius go back to the originaly generated state slowly)
water tool (somehow makes water, i remember hearing something along the lines of there only being 1 water material allowed per map, for some reason... idk if its true but if it is then the water gun would be very anoying to impliment as it would require a whole new implimentation of water, though could be similar to base hammer source water cubes)


additional features that would be so insane it would make me lose my mind: a standalone program for making the map, (if you were to make one id be highly suprised as your a single freaking developer of a map taht already pushes source past its limits, and thank you so much for the map) (also also if you do make it please please please, i run on linux and it would be nice if it ran either natively or fine under wine/proton)

**Comment by Mee12345** [comment]
1. lightning breaks when using a blendtexture, it also only supports 2 materials
2. performance rendering thousands of trees would be terrible
3. Water im afraid isn’t possible
4. no, if people see digging they will want caves, if they want caves then I have to make a voxel engine, which I cant imagine source handling well
5. using hammer would break my sanity

**Comment by Redd56** [comment]
Its completely fine, i honestly dont know the limits of the source engine as much as you. Hence why i really dont care if any of it gets implimented, as always thank you for the great addons youve brang in the past months, they have really pushed source beyond what we thought was possible.

**Comment by Unimox** [comment]
i mean we dont mean actual forests, just occasional trees scattered around the map

**Comment by willfromlondon** [comment]
Current chunk X/Y/Z exposed to wire would be amazingly handy for navigation - it's very easy to get lost in the world.  Maybe some kind of beacon?

**Comment by DarianLStephens** [comment]
I swear the main coordinates works in Wire, at least with the GPS. Doesn't it?

**Comment by willfromlondon** [comment]
Ah - you might be right! I was just using the console to navigate.

**Comment by Vinfinity-Gaming** [comment]
I have a suggestion, Make the installation easier (put it on steam, autoinstaller, anything but me having to input the files manually) I am having trouble installing the infinite map base. I wonder why no one else is complaining about this.

**Comment by DarianLStephens** [comment]
Because it's extremely easy?
You just download the code with the Github button to the top-right, extract it, and put iti n your addons folder.

**Comment by Mee12345** [comment]
closing since this isnt really an "issue", 

if you would like move suggestions to the discord or discussions tab
