### ISSUE TITLE
Loading Saves Spam errors and fling me

### ISSUE THREAD

**Issue by Unimox** [Mee12345/GMod-Infinite-Map#3]
Please can I get some help?

**Comment by Unimox** [comment]
And also objects arent saved correctly, they are moved slightly

**Comment by Mee12345** [comment]
can I have the error?

**Comment by Unimox** [comment]
Alright

**Comment by Unimox** [comment]
sorry about that i forgor about the error

**Comment by Mee12345** [comment]
closing issue since not enough information / save system appears to work fine
