### ISSUE TITLE
Npcs' A.I not working correctly and Star Wars Vehcile mod vehciles disappearing when entering a new chunk

### ISSUE THREAD

**Issue by bloodyframe2019** [Mee12345/gmod-infinite-map#38]
So when i try to enter a new chunk with a Star Wars vehicle. it disappears for no reason and Npcs' A.I doesn't work correctly onThe Infinite Terrain maps. Please fix.

**Comment by Mee12345** [comment]
AI will not be fixed because it is source internal, sorry.

As for the star wars vehicles, its probably their problem.. not sure how those work, is there a public repo I where can see the source code?

**Comment by bloodyframe2019** [comment]
> AI will not be fixed because it is source internal, sorry.
> 
> As for the star wars vehicles, its probably their problem.. not sure how those work, is there a public repo I where can see the source code?

again. you always find a way to make stuff happen and i do believe it is possible somehow. nothing is truely impossible just a challange. idk source code for the star wars vehicle mod and idk how to find it. however i am learning to ecome a programmer but i think i am a pretty far distence away from how much you know about programming.

also could you maybe readd the "classic" flat world infinite map?
btw love your mods. i was a part of your livestream from like 6 months ago with the procedual terrain mod.

**Comment by Mee12345** [comment]
wontfix
