### ISSUE TITLE
Does this work for dedicated servers?

### ISSUE THREAD

**Issue by BigGuyuefnazg** [Mee12345/GMod-Infinite-Map#40]
I have been trying to make it work on a server i bought for my friends, but the map doesnt seem to be working, i did the same thing you would do for the non-dedicated servers, but the map doesnt show up

**Comment by Mee12345** [comment]
it should work fine, what did you do with the files?

**Comment by pizzamagician** [comment]
skill issue (literally)

**Comment by pizzamagician** [comment]
is your server running on linux

**Comment by BigGuyuefnazg** [comment]
> it should work fine, what did you do with the files?

I just did the same thing that works for idk nondedicated servers, Put the file in the addons folder that is for the server and restarted the server

![image](https://user-images.githubusercontent.com/119203308/204260446-661c321f-68c4-4cbc-9ead-4b8389bb267f.png)


And to the guy who asked if it runs on linux, it does run on linux since the server has panel access or someshit
(I just asked the tech support ppl to change it to a vds so that it runs on windows instead, thanks for pointing that out)

**Comment by Mee12345** [comment]
whats the file structure? it has to be addons/infinitemap/lua/etc

**Comment by Mee12345** [comment]
im assuming it was a linux issue, hosting seems to work fine
