### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by nooberman12121** [Mee12345/GMod-Infinite-Map#42]
im kinda dumb so how do u intall this?

**Comment by hl2jeep** [comment]
> im kinda dumb so how do u intall this?

hover over the clone button on the main page, click download as zip, then open that zip and extract/copy the files from it, paste that folder from the zip file into C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons

**Comment by GOOFYAHHFARDNITEPRANKSTER1465872016** [comment]
> > im kinda dumb so how do u intall this?
> 
> hover over the clone button on the main page, click download as zip, then open that zip and extract/copy the files from it, paste that folder from the zip file into C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons

The problem is that when i do this it just doesn't paste in

**Comment by Unimox** [comment]
> 

restart your computer then try again

**Comment by wyattwins** [comment]
> > im kinda dumb so how do u intall this?
> 
> then open that zip and extract/copy the files from it

Do you mean open that zip and go in the folder? or is there more stuff inside the zip besides the folder holding the txt and lua and etc?

**Comment by wyattwins** [comment]
> Loading "..." songs By "Unknown Github User".

_Tap here to play nothing.._

**Comment by nooberman12121** [comment]
how did i just realize i spelled install wrong

**Comment by wyattwins** [comment]
i also just realized my brain is starting to run its things again so you dont have to reply.

**Comment by Mee12345** [comment]
basic instructions are to download the code and extract to addons folder, if this doesn't work please ask for help in the discord
