### ISSUE TITLE
[Suggestion] New terrain

### ISSUE THREAD

**Issue by KemGus** [Mee12345/GMod-Infinite-Map#46]
-Infinite desert
-Infinite snow mountain area, with a chance to find water

**Comment by Unimox** [comment]
oh this is a suggestion :(

**Comment by Unimox** [comment]
i thought this was a fork

**Comment by KemGus** [comment]
This map gave me an inspiration to put this suggestion here
![image](https://user-images.githubusercontent.com/42640259/205338443-b50a6f54-5a47-4c7c-9dec-dde5c9795dd4.png)

**Comment by Unimox** [comment]
anyway make your own desert, super easy

he will make water later
snow area MIGHT be added

**Comment by DarianLStephens** [comment]
I _would_ quite like to see biomes, but apparently the dynamic mesh thing Mee uses only supports 2 textures at a time.
I think that could still work, if chunks are split up in to separate meshes, by having carefully-considered 'transition chunks', which serve to blend between different biomes.

**Comment by Mee12345** [comment]
well… you can have 2 textures using something called a blendtexture… but it breaks all lighting so the idea was scrapped

**Comment by Mee12345** [comment]
closing since not technically an issue, move to discussions or to discord if you would like to discuss more about the possibility of this
