### ISSUE TITLE
i clip out of flying houses and an error with planets?

### ISSUE THREAD

**Issue by huxvap** [Mee12345/GMod-Infinite-Map#47]
error here:
[gmod-infinite-map-main] addons/gmod-infinite-map-main/lua/entities/infmap_planet.lua:292: attempt to index a nil value
    1. unknown - addons/gmod-infinite-map-main/lua/entities/infmap_planet.lua:292

when i reach a certain altitude i fall out of my up house
pls help

**Comment by Mee12345** [comment]
at the moment planets need Half Life: EP2 installed in order to work properly

as for falling out of your house, I think thats just source physics.

**Comment by Mee12345** [comment]
error is fixed, tree model is now compacted w/ mod
