### ISSUE TITLE
Switching chunks breaks visual clip rendering

### ISSUE THREAD

**Issue by TwistedTail** [Mee12345/GMod-Infinite-Map#5]
Only tested with Proper Clipping at the moment. The moment the player or clipped entity moves to another chunk, their clips will no longer be visible. The root seems to be the fact both Infinite Map and Proper Clipping mess with `ENT.RenderOverride`, so it's 100% an addon conflict. This conflict produces no errors.

How to replicate:
- Spawn a visclipped entity.
![Visclipped entity](https://user-images.githubusercontent.com/8784231/196071399-ea9ebf40-b4ac-49f1-b3b9-8b687636b9ad.png)
- Move to another chunk.
- Entity now has no visclips.
![Visclipped entity after moving to another chunk](https://user-images.githubusercontent.com/8784231/196071439-1bd6175e-a571-4fd8-870a-5fd9267d0d93.png)

**Comment by Mee12345** [comment]
fixed/

**Comment by DarianLStephens** [comment]
It seems that Stargates aren't too happy with it, still:
![20221022023129_1](https://user-images.githubusercontent.com/15375876/197234966-f4a4dc58-7918-46f2-b2cf-805d26c9887f.jpg)

![20221022023132_1](https://user-images.githubusercontent.com/15375876/197234970-3b280bec-993c-4b27-a4bc-a90aca4423da.jpg)

![20221022023145_1](https://user-images.githubusercontent.com/15375876/197235024-a353a8c0-9d95-43a5-b961-b7821ac24225.jpg)
