### ISSUE TITLE
Addon not teleporting contraptions

### ISSUE THREAD

**Issue by MissKay1994** [Mee12345/gmod-infinite-map#52]
I've been messing with the addon, and found an issue where after adding 1 additional E2 to my ACF car to do an odometer, the car ceases to work with the chunks teleportation. I can still see the car there and I'm in it, but the car physically no longer exist where I am seeing it combined with I am driving into a map wall instead of being teleported

**Comment by Mee12345** [comment]
Are you using a setang plate? 
setang plates are not compatible

**Comment by MissKay1994** [comment]
I have a setang steering, but that's never been an issue before. My best guess is maybe something related to adding additional holo's with an odometer

**Comment by Mee12345** [comment]
could you send the dupe?

**Comment by pizzamagician** [comment]
yeah e2 setang steering doesn't work

**Comment by MissKay1994** [comment]
I can happily send a copy. After a bit of messing around I think the problem is related to it doesn't like things with more than a certain amount of entities. Do you have a place I can send you it such as Discord since I don't really want to post my dupe on the internet for everyone?

**Comment by Mee12345** [comment]
my guess is its the setang steering causing issues. ill make an acf “tutorial” at some point explaining why this happens

if interested I think this github has a link to the discord in the readme

**Comment by Mee12345** [comment]
issue is related to setang steering which doesn't work
