### ISSUE TITLE
to Mee12345

### ISSUE THREAD

**Issue by KemGus** [Mee12345/GMod-Infinite-Map#54]
Hi, you're awesome! Hopefully you won't lose your motivation on this and get this revolutionary project done!

Big **Thank you** from everyone!
![image](https://user-images.githubusercontent.com/42640259/205486231-37f13ede-604c-4394-b3f9-283babe77a15.png)

https://www.youtube.com/watch?v=ZoOfqoGF6Oo

Sincerely, 
Garry's Mod community

**Comment by KemGus** [comment]
(anyone can post his gameplay pictures on inf map here and leave your words)

**Comment by KemGus** [comment]
![image](https://user-images.githubusercontent.com/42640259/206225931-deab7b5b-e78a-473a-a872-e5f038abda34.png)

**Comment by KemGus** [comment]
The very first flight on inf map

**Comment by DarianLStephens** [comment]
A friend and I went flying a few weeks ago in a wire-controlled vehicle we built, using Gravity Hull Designator so we could do things in the back while flying.

**Comment by Mee12345** [comment]
preciate it mate, but ima close this issue though since it isn't really an "issue"

(feel free to move to discussions tab)
