### ISSUE TITLE
BUG: Why i cant take a weapon outside of the original map?

### ISSUE THREAD

**Issue by Kekusich** [Mee12345/gmod-infinite-map#56]
https://user-images.githubusercontent.com/120040622/206486320-46d2ae37-fdf1-4eac-a3b1-b64a39c37f82.mp4

**Comment by Mee12345** [comment]
hm, I don't have this problem, have you checked for any conflictions?

**Comment by Kekusich** [comment]
i will try it at vanilla gmod

**Comment by Mee12345** [comment]
was this ever fixed?

**Comment by Mee12345** [comment]
noreply
