### ISSUE TITLE
Planet surfaces appear as couches.

### ISSUE THREAD

**Issue by MKemp28** [Mee12345/GMod-Infinite-Map#58]
It must be something wrong with the way I have installed the mod, but the surfaces of planets are couches with materials corresponding to their exterior texture. For example, when I fly into "Earth's" atmosphere, instead of there being land inside there is a couch. It has a grass material on it. Mars has red sand, Uranus has blue sand and so on. How do I fix this?

**Comment by Mee12345** [comment]
only thing I can say is to check for addon confliction, if you find one can you report which one it is?

**Comment by MKemp28** [comment]
> only thing I can say is to check for addon confliction, if you find one can you report which one it is?

I'll check that as soon as I can. Will do! Thank ya

**Comment by MKemp28** [comment]
> only thing I can say is to check for addon confliction, if you find one can you report which one it is?

After disabling all addons, the planet's surfaces still appear as couches. The planet's collisions are still there; It just appears to me a mistake on my end.

**Comment by Mee12345** [comment]
hm. when is the last time you updated? I don't know anyone else with the issue

**Comment by MKemp28** [comment]
Uhhhhhh, it should be completely up to date. Gmod is up to date, and I reinstalled the mod too. I checked the "problems" section of Garry's Mod, and this error appears whenever I noclip into a planet's atmosphere.

lua/entities/infmap_planet.lua:292: attempt to index a nil value
    1. unknown - lua/entities/infmap_planet.lua:292

**Comment by Unimox** [comment]
> Uhhhhhh, it should be completely up to date. Gmod is up to date, and I reinstalled the mod too. I checked the "problems" section of Garry's Mod, and this error appears whenever I noclip into a planet's atmosphere.
> 
> lua/entities/infmap_planet.lua:292: attempt to index a nil value 1. unknown - lua/entities/infmap_planet.lua:292

He meant update the mod, every new commit you will have to manually install it again

**Comment by Mee12345** [comment]
yeah it sounds like you just havent updated, that code isnt called anymore when you enter a planet

**Comment by MKemp28** [comment]
No worries. Knew it must have been my bad lmao. Thanks
