### ISSUE TITLE
Chunk Sound Bug

### ISSUE THREAD

**Issue by mrwallace888** [Mee12345/GMod-Infinite-Map#62]
Sounds go quiet when crossing chunks, depending on the sound.

For example, when driving a simfphys vehicle, the turbocharger whine plays between chunks, but once you leave the original chunk you were in, the car will stop playing the turbo's blow-off valve sound permanently when letting off the throttle.

Or if you leave a car running, move away to another chunk or somewhere in the distance, then come back, the car will be completely silent. All of its sounds will remain permanently silent, so it'll still remain quiet if you rev the engine and stuff. The majority of its sounds will return after driving for a little bit, though some still remain silent.

**Comment by Mee12345** [comment]
unfortunately wont fix because source sounds are retarded, once you stop a sound you cant start it again

**Comment by Mee12345** [comment]
nevermind! wfl made rewrote the sounds implementation
