### ISSUE TITLE
make a setpos command that works better

### ISSUE THREAD

**Issue by LucasAiden** [Mee12345/GMod-Infinite-Map#69]
like "infmap_setpos 69420 69420 69420"

**Comment by ArsWarsAlmaz** [comment]
`lua_run Entity(1):SetPos(Vector(69420,69420,69420))`

**Comment by Mee12345** [comment]
wdym works better, im not aware of any sepos command other than the lua one which is already detoured

**Comment by shadow7483147** [comment]
think he means the console command `setpos`
