### ISSUE TITLE
Bad collisions on faraway coordinates

### ISSUE THREAD

**Issue by blackflash4088** [Mee12345/gmod-infinite-map#70]
Collisions are broken on faraway terrain and I'm guessing this also includes all planets.

Basically, after dropping down onto any terrain very distant from spawn, I get stuck on it for a few seconds unable to move, then clip through it. The extent to which this happens varies depending on the complexity of the terrain.

**Comment by Mee12345** [comment]
how far? can I have the exact chunk position?

**Comment by Mee12345** [comment]
ive gone to chunks 0-0, 64-64, 128-128, 256-256, 512-512, 1024-1024, 2048-2048, 4096-4096 and 65536-65536 and none of them had issues. 

do you have vphysics jolt installed or anything like that?
have you checked for addon conflictions?

**Comment by Norway174** [comment]
I noclipped at super speed up to 10 million meters away from Spawn. I didn't have any collision issues when I spawned myself a car and drove around some, at that distance.

Just figured I'd share, in case that helps narrow it down. Not sure if anyone has been that far out yet?
![gmod_2022-12-14_21-41-50](https://user-images.githubusercontent.com/4808657/207712787-d3b62da6-7af9-44d1-af60-bf79b881ab61.png)

**Comment by blackflash4088** [comment]
Thanks for checking this and sharing. It's really late now, so tomorrow, I'll try disabling my addons to see if that's the issue. If I somehow manage find the culprit, I'll share it here.

BTW, I barely know what lua is, so yeah...

**Comment by blackflash4088** [comment]
It doesn't seem to be a particular chunk in which the problem occurs. It happens when I set noclip speed to 5000 and fly at max speed for 10 seconds. That's the best description I can give you as of now.

I also just recalled that I have set my physics iterations setting to a lower quality due to some unrelated simfphys issue. Do have a look at that.

**Comment by blackflash4088** [comment]
The addon causing this issue is "Walk on Moving Props!"

**Comment by Mee12345** [comment]
well I think thats your confliction, can ya send the error message exactly?

**Comment by blackflash4088** [comment]
It's not a lua conflict. Read the addon description and you'll probably have an idea of why this problem occurs.

**Comment by Mee12345** [comment]
havent had anyone else with this issue, so either its fixed or not reproducible
