### ISSUE TITLE
Vphysics Jolt & Mee's Seamless Portals incompatability with this mod.

### ISSUE THREAD

**Issue by OutlandJoe** [Mee12345/GMod-Infinite-Map#73]
I've found that while using Vphysics Jolt AND your seamless portals mod in an infinite map, props will get caught in the map's edges. They won't move to the new chunk. I've noticed this is more of a vertical issue then horizontal I believe. 

I have no real way to describe the issue further I apologize. 

But I hope this isn't a big problem that'll be impossible or far too difficult to fix.

Otherwise it seems if I DON'T use seamless portals Vphysics Jolt works perfectly.

Only catch is spawning anything (like props) from the spawn menu seems to not spawn on the terrain.
Works for "planet" terrains but not the main terrain.

I hope my Issue was concise and might lead to a possible solution.

Also i'm just going to throw this out there if i've caught your attention, have you ever considered utilizing seamless portals to make a modern "Gravity Hull Designator" of sorts? It seems possible with that technology. Just asking since I love that sort of stuff. Thanks if you've for your time if you've read this.

**Comment by Mee12345** [comment]
vphysics jolt isnt compatible no matter what addons are used because for whatever reason the physics engine can't no collide objects so you end up colliding with everything in all chunks

**Comment by Mee12345** [comment]
closing since vphysics jolt incompatibility
