### ISSUE TITLE
Having Issues With LFS Vehicles disappears when entering chunks

### ISSUE THREAD

**Issue by ghost** [Mee12345/gmod-infinite-map#75]
Now for some reason for most of the LFS Vehicles I have tested, they tend to disappear when you enter a chunk, but a few chunks away, you can see the vehicle that you are driving, I will link the source code to the vehicles i have tried so far, so basically if the vehicle is big, it doesn't render the chunk that you are in.

https://user-images.githubusercontent.com/78246226/208147112-d15cc7c9-62f7-4548-960c-74d2d79f2243.mp4

 (I also attached a video to show you)

[LFS] MI-28 Battle Hind: https://www.mediafire.com/file/znln9xn4cvd2xjr/lfs+vehicles+i+have+tested.7z/file

[LFS] - Planes (Base): https://github.com/Blu-x92/LunasFlightSchool

**Comment by Mee12345** [comment]
I havent had any issues with normal lfs planes/helicopter, it could be the helicopter addon itself causing issues

**Comment by Gabriel-Morales805** [comment]
@Mee12345 Same here, i beleive the aircraft size could be to blame.

**Comment by Mee12345** [comment]
LFS has been replaced with LVS which has better infmap support, so this is a little obsolete
