### ISSUE TITLE
Some looped sounds don't stop when they should.

### ISSUE THREAD

**Issue by mrwallace888** [Mee12345/gmod-infinite-map#77]
Glad to see Will's detours got sounds working significantly better. But there's a small downside. I was driving a Simfphys vehicle and noticed that when I turned it off, the engine sound still played, as well as sounds for the supercharger, and occasionally tire rolling/skidding sounds.

There was also some simfphys cars I have that use a script that play a looping ignition sound before turning the car on, and the ignition sound continues to loop afterwards.

The only way for me to get rid of looped sounds is by going into Xala's Movie Helper and cleaning up sounds. Else they'll just play forever.

While Will's patches worked, I don't understand why they don't like looped sounds. Unless it's like... it's either before where it stops playing a looped sound when it should keep playing, or you force it to keep playing forever?

**Comment by Mee12345** [comment]
you'll have to ask will on that one

**Comment by mrwallace888** [comment]
There a way to ping him?
