### ISSUE TITLE
Main folder name is incompatible with gmod on linux (easy to fix)

### ISSUE THREAD

**Issue by Scott-McKool** [Mee12345/gmod-infinite-map#80]
In Linux, capitals matter when naming folders. and for some reason if the main folder of an addon has capitals then gmod just won't load it.

Just change "GMod-Infinite-Map" to "gmod-infinite-map" and it will work with linux.

**Comment by Scott-McKool** [comment]
I would have made a PR, but i don't think you can change things like the repository's name in a pull request. . .

**Comment by Mee12345** [comment]
ah, so sorry I forgot about linuxes file system

**Comment by Mee12345** [comment]
should be changed
