### ISSUE TITLE
Frequent Collisions With World Border When Going Over 200kmh (Simfphys)

### ISSUE THREAD

**Issue by HolidayTheBoi** [Mee12345/gmod-infinite-map#82]
Heya, just wanted to grab some attention to this if this hasn't already been talked about or such, but it seems when going above 200kmh in Simfphys vehicles they frequently won't teleport fast enough. You can see this in this video I have taken of this effect as it happens currently.

[Video Example](https://youtu.be/Gjr0ncJ0oRw)

**Comment by Mee12345** [comment]
hm.. i think this is related to tickrate

I did a recent change to the max speed so its likely that is the problem, should be fixed soon

**Comment by HolidayTheBoi** [comment]
Hello again! I wanted to leave this for future people having this issue. After doing like 2 hours of testing enabling and disabling mods it seems that this issue of the speed being capped and freaking out the world seems to be caused by a mod called [SW Bombs](https://steamcommunity.com/sharedfiles/filedetails/?id=2609986388). 

After disabling this mod I had no issues other than the expected visual lag every now and then.
