### ISSUE TITLE
HL2 jeep not working?

### ISSUE THREAD

**Issue by titanicjames** [Mee12345/gmod-infinite-map#84]
I have not seen the jeep act like this before.

https://user-images.githubusercontent.com/86326144/208623538-016ec58e-1828-4b98-8954-e89f1bb7ea68.mp4

as you can see, it seems the tires decide to act as though the ground does not exist.

**Comment by Mee12345** [comment]
jeeps are intentionally broken as they cant have their position set

**Comment by DarkReaper231** [comment]
> jeeps are intentionally broken as they cant have their position set

LW cars do the same thing. Are they based on Jeep thus intentionally broken or is it more of a side effect? Could you make LW cars work? It's one of the best high quality vehicle mod.

**Comment by Mee12345** [comment]
LW cars are jeep physics based, and are also intentionally broken

its possible to fix, but the side effect comes in as *way* worse performance and prediction issues on the terrain because i would be changing how source handles its physics on that entity

**Comment by Mee12345** [comment]
right now im using movetype:none instead of movetype:physics which helps performance a lot and breaks jeeps as a side effect (which dont work anyways so I don’t really care to fix them)

**Comment by Mee12345** [comment]
(besides, simphys are better imo)

**Comment by DarkReaper231** [comment]
I ditched LW and downloaded all the simphys cars from Willi302. Gotta tell, that's a giant collection of cars.

**Comment by titanicjames** [comment]
Well, i suppose that explains it. Concessions are concessions...
