### ISSUE TITLE
Particle and explosion detour only kinda works

### ISSUE THREAD

**Issue by PilvinenPaiva** [Mee12345/gmod-infinite-map#85]
Whenever I blow up something in a another chunk, an identical copy of the explosion spawns in the chunk I'm currently in. Sometimes the original also just disappears a few seconds after spawning. Also there's some other weird stuff with them following you. Particles don't work any differently than in previous updates either, though the only reason I posted this was because at least the explosions were directly demonstrated working in the newest devlog/clip.
I tried this multiple times with all addons expect Hbombs disabled, so it shouldn't be a conflict.

Am I understanding something wrong or is there just a bug?

https://user-images.githubusercontent.com/113588675/208654248-d01eff8a-82e2-41ab-bb30-8353722e3920.mp4

**Comment by Mee12345** [comment]
yeah welcome to source. you cant clear a particle so youre gonna get that following effect no matter what you do. the detour is not perfect but its the best I can do

as for the particle appearing 2 times, thats pretty weird.. ill see if I can figure out the problem there.
