### ISSUE TITLE
Game Crashes upon opening

### ISSUE THREAD

**Issue by matt122501** [Mee12345/gmod-infinite-map#89]
Is there someway to fix this i am wondering if installed something wrong

**Comment by Mee12345** [comment]
see https://github.com/Mee12345/gmod-infinite-map/issues/41

**Comment by matt122501** [comment]
Tried that the game works now but it does not look as intended it looks like this 
![image](https://user-images.githubusercontent.com/41029934/208966849-54901ce9-d227-43b9-9d15-e6cef733f339.png)

**Comment by matt122501** [comment]
![image](https://user-images.githubusercontent.com/41029934/208967057-0c26da1a-7a20-4332-bb3b-3a9ab5783bc1.png)
