### ISSUE TITLE
Script errors on new map versions

### ISSUE THREAD

**Issue by fedorissimo** [Mee12345/gmod-infinite-map#91]
![изображение](https://user-images.githubusercontent.com/91797262/209103714-2cac7296-617b-410e-9d98-1575518ab902.png)

**Comment by fedorissimo** [comment]
I also can't go faster than 200KM/H

**Comment by fedorissimo** [comment]
Everything is OK on normal maps and on previous infinite map versions

**Comment by Mee12345** [comment]
fixed, thanks for reporting
