### ISSUE TITLE
JMod explosions are bugged.

### ISSUE THREAD

**Issue by Autumnis** [Mee12345/gmod-infinite-map#93]
When a JMod explosive detonates, the explosion teleports to the current chunk/area/whatever the player is in. Haven't tested it in multiplayer.

**Comment by Autumnis** [comment]
don't know how to add labels, sorry.

**Comment by MKemp28** [comment]
I have the same issue with Hbombs. I assumed it was just impossible/too hard to fix.

**Comment by Mee12345** [comment]
unfortunately you cant detour serverside particles, sorry.
