### ISSUE TITLE
"Material URL Tool (Beta)" addon causes map to be wire mesh

### ISSUE THREAD

**Issue by cottondell** [Mee12345/gmod-infinite-map#97]
The **"Material URL Tool (Beta)"** addon causes the map to be a wire mesh texture as opposed to the grass texture.
Addon link: https://steamcommunity.com/sharedfiles/filedetails/?id=2559426779

**Comment by Mee12345** [comment]
thats super odd
should be fixed next patch, I didn't feel like sorting thru the addons code so I just put setmaterial in the hook where the bounds are updated
